#  Main Configuration

# Author Ph1Lou

# Link :

# Version 1.0

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2019


default_lobby: true
training: false
tournament: false
number_team_auto_start: 4


