#  Main Configuration

# Author Ph1Lou

# Link :

# Version 1.1

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2025


default_lobby: true
training: false
number_team_auto_start: 4


