name: Space_Conquest
version: "1.0"
author: Ph1Lou
main: fr.ph1lou.space_conquest.Main
depend:
  - Citizens
api-version: 1.16
commands:
  stop:
    description: pour forcer la fin de game
  t:
    description: chat de team
  load:
    description: reload la db
